rm run.sh
# python sendOnBatch.py Run2012A            >> run.sh
# python sendOnBatch.py Run2012B            >> run.sh
# python sendOnBatch.py Run2012C_1          >> run.sh
# python sendOnBatch.py Run2012C_2          >> run.sh
# python sendOnBatch.py Run2012C_3          >> run.sh
# python sendOnBatch.py Run2012D_1          >> run.sh
# python sendOnBatch.py Run2012D_2          >> run.sh
# python sendOnBatch.py Run2012D_3          >> run.sh
# python sendOnBatch.py G_Pt-50to80      	  >> run.sh  
# python sendOnBatch.py G_Pt-80to120   	  >> run.sh
# python sendOnBatch.py G_Pt-120to170  	  >> run.sh
# python sendOnBatch.py G_Pt-170to300  	  >> run.sh
# python sendOnBatch.py G_Pt-300to470  	  >> run.sh
# python sendOnBatch.py G_Pt-470to800  	  >> run.sh
# python sendOnBatch.py QCD_Pt-80to120 	  >> run.sh 
# python sendOnBatch.py QCD_Pt-120to170 	  >> run.sh
# python sendOnBatch.py QCD_Pt-170to300 	  >> run.sh
# python sendOnBatch.py QCD_Pt-300to470     >> run.sh
# python sendOnBatch.py QCD_Pt-470to600 	  >> run.sh
# python sendOnBatch.py QCD_Pt-600to800 	  >> run.sh
# python sendOnBatch.py QCD_Pt-800to1000 	  >> run.sh
# python sendOnBatch.py QCD_Pt-1000to1400   >> run.sh
# python sendOnBatch.py TTJets  		  >> run.sh
# python sendOnBatch.py GMSB_L180-CTAU500   >> run.sh
# python sendOnBatch.py GMSB_L180-CTAU10    >> run.sh
# python sendOnBatch.py GMSB_L180-CTAU50    >> run.sh
# python sendOnBatch.py GMSB_L180-CTAU250   >> run.sh
# python sendOnBatch.py GMSB_L160-CTAU500   >> run.sh
python sendOnBatch.py GMSB_L160-CTAU100   >> run.sh
# python sendOnBatch.py GMSB_L160-CTAU10    >> run.sh
# python sendOnBatch.py GMSB_L160-CTAU250   >> run.sh
# python sendOnBatch.py GMSB_L160-CTAU50    >> run.sh
